version: "3.7"
services:
  nginx:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - "8090:80"
    volumes:
      - ./nginx/project.conf:/etc/nginx/conf.d/default.conf
      - .:/project

  php:
    image: php:7.3-fpm
    expose:
      - "9000"
    volumes:
      - .:/project

  composer:
    image: composer:latest
    volumes:
      - ./api:/app
    command: composer install

  node:
    image: node:12
    volumes:
      - ./app:/project

