version: "3.7"
services:
  nginx:
    image: nginx:stable
    depends_on:
      - phpfpm
      - app
    expose:
      - "80"
    ports:
      - "3000:80"
    volumes:
      - ./nginx/project.conf:/etc/nginx/conf.d/default.conf
      - .:/project

  phpfpm:
    image: php:7.3-fpm
    expose:
      - "9000"
    volumes:
      - .:/project

  php:
    image: php:7.3
    volumes:
      - ./api:/api
    working_dir: /api

  composer:
    image: composer:latest
    volumes:
      - ./api:/app
    command: composer update

  app:
    image: node:12
    expose:
      - "3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start

